name: Docker Run Action Tests

on:
  push:
    branches:
      - prime
      - develop
  pull_request_review:
    types: [submitted]

jobs:
  smoke-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: https://github.com/actions/checkout@v5
      - name: Run docker action and set output for testing
        uses: ./
        id: run-docker
        with:
          image: docker:27.4.0
          run: |
            echo "docker-version=$(echo $DOCKER_VERSION)" >> $GITHUB_OUTPUT
      - name: Test the output
        uses: https://github.com/actions/github-script@v8
        with:
          script: |
            const dockerVersion = '${{ steps.run-docker.outputs.docker-version }}';
            if (dockerVersion !== '27.4.0') {
              core.setFailed(`Smoke Test Failed`);
            }
  volume-mount-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: https://github.com/actions/checkout@v5
      - name: Create File to be mounted
        run: echo "some text" > someFile
      - name: Run docker action with mounted workspace
        uses: ./
        id: run-docker
        with:
          image: docker
          options: -v=${{ github.workspace }}:/work
          run: |
            echo "file-contents=$(cat /work/someFile)" >> $GITHUB_OUTPUT
      - name: Check if file contents match
        uses: https://github.com/actions/github-script@v8
        with:
          script: |
            const fileContents = '${{ steps.run-docker.outputs.file-contents }}';
            if (fileContents !== 'some text') {
              core.setFailed(`Unable to mount workspace volume`);
            }
  ws-mount-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: https://github.com/actions/checkout@v5
      - name: Create File to be mounted
        run: echo "some text" > someFile
      - name: Run docker action with mounted workspace
        uses: ./
        id: run-docker
        with:
          image: docker
          mount_ws: true
          run: |
            echo "file-contents=$(cat ./someFile)" >> $GITHUB_OUTPUT
      - name: Check if file contents match
        uses: https://github.com/actions/github-script@v8
        with:
          script: |
            const fileContents = '${{ steps.run-docker.outputs.file-contents }}';
            if (fileContents !== 'some text') {
              core.setFailed(`Unable to mount workspace volume`);
            }
  tmp-mount-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: https://github.com/actions/checkout@v5
      - name: Create File to be mounted
        run: echo "some text" > /tmp/someFile
      - name: Run docker action with mounted workspace
        uses: ./
        id: run-docker
        with:
          image: docker
          mount_ws: /tmp
          run: |
            echo "file-contents=$(cat /tmp/someFile)" >> $GITHUB_OUTPUT
      - name: Check if file contents match
        uses: https://github.com/actions/github-script@v8
        with:
          script: |
            const fileContents = '${{ steps.run-docker.outputs.file-contents }}';
            if (fileContents !== 'some text') {
              core.setFailed(`Unable to mount workspace volume`);
            }
  container-network-test:
    runs-on: ubuntu-24.04
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_USER: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 5s --health-timeout 5s --health-retries 10
    steps:
      - uses: https://github.com/actions/checkout@v5
      - name: Run docker action and test network connection
        uses: ./
        with:
          image: postgres
          run: >
            pg_isready -d test -U test -h postgres -p ${{ job.services.postgres.ports[5432] }}
          options: >
            -e=PGPASSWORD=test
